 # Generated by Django 4.1.3 on 2022-11-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_fielad', models.IntegerField()),
                ('char_fiald', models.CharField(max_length=10)),
                ('date_fiels', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
