# Generated by Django 4.1.3 on 2022-11-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='date_fiels',
        ),
        migrations.RemoveField(
            model_name='example',
            name='email',
        ),
    ]
